.gitignore, README.md, apps/neoscan/lib/neoscan/addresses/addresses.ex, apps/neoscan/lib/neoscan/addresses/history.ex, apps/neoscan/lib/neoscan/application.ex, apps/neoscan/lib/neoscan/blocks/block.ex, apps/neoscan/lib/neoscan/blocks/blocks.ex, apps/neoscan/lib/neoscan/transactions/asset.ex, apps/neoscan/lib/neoscan/transactions/transaction.ex, apps/neoscan/lib/neoscan/transactions/transactions.ex, apps/neoscan/lib/neoscan/transactions/vout.ex, apps/neoscan/mix.exs, apps/neoscan/neoscan.iml, apps/neoscan/test/addresses/addresses_test.exs, apps/neoscan/test/blocks/blocks_test.exs, apps/neoscan/test/support/data_case.ex, apps/neoscan/test/support/factory.ex, apps/neoscan/test/transactions/transactions_test.exs, apps/neoscan_monitor/config/config.exs, apps/neoscan_monitor/neoscanmonitor.iml, apps/neoscan_sync/neoscansync.iml, apps/neoscan_web/neoscanweb.iml
Fix the tests. First step before adding more tests.
=> Fix the tests

apps/neoscan/lib/neoscan/helpers/helpers.ex, apps/neoscan_web/lib/neoscan_web/controllers/address_controller.ex, apps/neoscan_web/lib/neoscan_web/controllers/assets_controller.ex, apps/neoscan_web/lib/neoscan_web/controllers/transaction_controller.ex, apps/neoscan_web/lib/neoscan_web/templates/address/address.html.eex, apps/neoscan_web/lib/neoscan_web/views/addresses_view.ex
Put Utility function in Helper Module
=> Code improviment

README.md
This seems like it should be written as code.
=> Change layout

.gitignore, .travis.yml
Minor version changes for both elixir and otp
=> Update elixir version and otp version in travis

.gitignore, apps/neoscan_web/lib/neoscan_web/templates/layout/app.html.eex
Adding the title for google search results.
closes #34
=> add website description

apps/neoscan_web/lib/neoscan_web/templates/layout/app.html.eex
Reverts CityOfZion/neo-scan#46
=> Revert "add website description"

apps/neoscan_sync/mix.exs, mix.lock
this potentially fixes the root cause of the connect_timeout problems, see:
https://github.com/benoitc/hackney/issues/420
=> update hackney to 1.11

apps/neoscan_web/lib/neoscan_web/plugs/locale.ex, apps/neoscan_web/lib/neoscan_web/templates/layout/app.html.eex, apps/neoscan_web/lib/neoscan_web/views/layout_view.ex, apps/neoscan_web/priv/gettext/nl/LC_MESSAGES/default.po, apps/neoscan_web/priv/gettext/nl/LC_MESSAGES/errors.po
Introducing the Dutch language to NEOSCAN.
Because of the lack of a PR template i'll take another one from another repo.
**What current issue(s) from Github does this address?**
None
**What problem does this PR solve?**
The lack of a language
**How did you solve this problem?**
By translating to Dutch
**How did you make sure your solution works?**
Testing and running
**Are there any special changes in the code that we should be aware of?**
No
**Is there anything else we should know?**
No
=> Introducing the Dutch language (Nederlands)

apps/neoscan/priv/repo/migrations/20180518101249_add_address_index.exs
=> add index on address updated_at after postgresql analysis

README.md, apps/neoscan/config/dev.exs, apps/neoscan/config/test.exs, apps/neoscan_web/assets/package-lock.json, docker-compose.yml
Make config easier for a quick start
=> fix readme and docker compose to simplify startup

docker-compose.prod.yml, haproxy/haproxy.cfg
Enable haproxy stats to collect it on datadog
=> add stats to haproxy

.gitlab-ci.yml, docker-compose.prod.yml
Limit log files from docker to avoid filling up the disk (max 1GB)
=> Docker logging

apps/neoscan_web/lib/neoscan_web/plugs/locale.ex, apps/neoscan_web/lib/neoscan_web/templates/layout/app.html.eex, apps/neoscan_web/lib/neoscan_web/views/layout_view.ex, apps/neoscan_web/priv/gettext/es/LC_MESSAGES/default.po, apps/neoscan_web/priv/gettext/es/LC_MESSAGES/errors.po
=> Add Spanish traslated

apps/neoscan_cache/lib/neoscan_cache/utils.ex, apps/neoscan_node/config/config.exs, apps/neoscan_node/lib/neoscan_node/notifications/notifications.ex, apps/neoscan_web/config/prod.exs
- Remove incorrect server (notifications4)
- Add delay before retrying a notification query
- set check_origin to false to allow websocket loading from any domain
=> Modification on notifications server

apps/neoscan_node/config/config.exs, apps/neoscan_node/lib/neoscan_node/notifications/notifications.ex
Fix notifications server endpoint, if notification server is not at the right height it will test other ones. Add back notification 4 server
=> fix notifications

apps/neoscan/lib/neoscan/blocks/block.ex, apps/neoscan/lib/neoscan/blocks/blocks.ex, apps/neoscan_web/lib/neoscan_web/templates/blocks/blocks.html.eex, apps/neoscan_web/lib/neoscan_web/views/blocks_view.ex
=> get block delay with window function

apps/neoscan_web/assets/js/app.js, apps/neoscan_web/lib/neoscan_web/templates/addresses/addresses.html.eex, apps/neoscan_web/lib/neoscan_web/templates/block/block.html.eex, apps/neoscan_web/lib/neoscan_web/templates/blocks/blocks.html.eex, apps/neoscan_web/lib/neoscan_web/templates/shared/transactions_wrapper.html.eex, apps/neoscan_web/lib/neoscan_web/templates/transaction/transaction.html.eex, apps/neoscan_web/lib/neoscan_web/views/common_view.ex
=> Fix utc time

apps/neoscan/lib/neoscan/blocks/blocks.ex
=> change seconds to epoch

apps/neoscan/lib/neoscan/addresses/addresses.ex, apps/neoscan/test/addresses_test.exs, apps/neoscan_web/assets/js/home_app.js
close #243 close #242 close #147
=> fix address chart

CHANGELOG.md, Dockerfile, apps/neoscan_web/lib/neoscan_web/controllers/address_controller.ex, apps/neoscan_web/lib/neoscan_web/controllers/block_controller.ex, apps/neoscan_web/lib/neoscan_web/controllers/transaction_controller.ex, apps/neoscan_web/lib/neoscan_web/controllers/transactions_controller.ex, apps/neoscan_web/lib/neoscan_web/helper.ex, apps/neoscan_web/lib/neoscan_web/templates/shared/transaction_panel.html.eex, apps/neoscan_web/lib/neoscan_web/templates/shared/transaction_panel_entries.html.eex, rel/config.exs
=> Refactor transaction panel

apps/neoscan/lib/neoscan/addresses/addresses.ex, apps/neoscan/test/addresses_test.exs, apps/neoscan_node/test/neoscan_node/http_calls_test.exs, apps/neoscan_web/lib/neoscan_web/api.ex, apps/neoscan_web/test/neoscan_web/controllers/api_controller_test.exs
=> fix mint instead of claim issue

apps/neoscan_node/lib/neoscan_node/blockchain.ex, apps/neoscan_node/lib/neoscan_node/node_checker.ex, apps/neoscan_node/test/neoscan_node/blockchain_test.exs
=> Invalid height is returning from get_node_height/1

apps/neoscan_node/lib/neoscan_node/blockchain.ex, apps/neoscan_node/lib/neoscan_node/node_checker.ex, apps/neoscan_node/test/neoscan_node/blockchain_test.exs
=> Rename get node height

apps/neoscan/lib/neoscan/addresses/addresses.ex, apps/neoscan/test/addresses_test.exs, apps/neoscan_web/lib/neoscan_web/api.ex, apps/neoscan_web/test/neoscan_web/controllers/api_controller_test.exs
Add following case to tx abstracts:
- pay fees with gas (instead of claim)
- miner receive network fees (instead of claim)
- send token to no address is a burn
close #276
=> correct tx abstracts from and to value

apps/neoscan/test/addresses_test.exs, apps/neoscan_web/lib/neoscan_web/api.ex, apps/neoscan_web/lib/neoscan_web/controllers/api_controller.ex, apps/neoscan_web/lib/neoscan_web/endpoint.ex, apps/neoscan_web/test/neoscan_web/controllers/api_controller_test.exs
=> fix get block and get transaction return if block or transaction does not exist

apps/neoscan/lib/neoscan/blocks/blocks.ex, apps/neoscan/priv/repo/migrations/20180607000003_vouts.exs, apps/neoscan/test/transactions_test.exs, apps/neoscan_web/lib/neoscan_web/api.ex
=> optimize missing block query

apps/neoscan/config/config.exs, apps/neoscan/lib/neoscan/addresses/addresses.ex, apps/neoscan/test/addresses_test.exs, apps/neoscan_web/assets/css/styles.css, apps/neoscan_web/lib/neoscan_web/templates/address/address.html.eex
=> add deprecated tokens

apps/neoscan_web/assets/css/styles.css
fix #148 
screen-shot a bit foggy, it's on a VM
=> Quickfix currencies select options not visible

apps/neoscan/lib/neoscan/blocks/blocks_cache.ex, apps/neoscan/lib/neoscan/blocks/segment_tree.ex, apps/neoscan/test/blocks_test.exs, apps/neoscan_web/lib/neoscan_web/api.ex, apps/neoscan_web/test/neoscan_web/controllers/api_controller_test.exs
=> Optimize gas calculation

apps/neoscan_web/assets/js/home_app.js
=> Fix the javascript error in address page if users didn't have NEO before

apps/neoscan/lib/neoscan/addresses/addresses.ex, apps/neoscan/test/addresses_test.exs
=> remove network fees for gas transfer

apps/neoscan_web/test/neoscan_web/controllers/api_controller_test.exs
=> Fix the missing document issue for the get_last_transactions_by_address API

apps/neoscan/lib/neoscan/addresses/addresses.ex, apps/neoscan/test/addresses_test.exs
=> Fix the incorrect fee for the get_address_abstracts API

apps/neoscan/priv/repo/migrations/20180607000002_transactions.exs, apps/neoscan/priv/repo/migrations/20180607000003_vouts.exs, apps/neoscan/priv/repo/migrations/20180607000006_address_histories.exs, apps/neoscan/priv/repo/migrations/20180607000013_address_transaction_balances.exs
=> Index cleanup

apps/neoscan_web/lib/neoscan_web/api.ex, apps/neoscan_web/test/neoscan_web/controllers/api_controller_test.exs
=> fix decimal rendering

apps/neoscan/lib/neoscan/transactions/transaction.ex, apps/neoscan/lib/neoscan/transactions/transactions.ex, apps/neoscan/lib/neoscan/transactions/vin.ex, apps/neoscan/priv/repo/migrations/20180607000002_transactions.exs, apps/neoscan/priv/repo/migrations/20180607000004_vins.exs, apps/neoscan/test/support/factory.ex, apps/neoscan_cache/test/support/factory.ex, apps/neoscan_sync/lib/neoscan_sync/converter.ex, apps/neoscan_web/test/support/factory.ex
=> Keep the order of vins and transactions

apps/neoscan/lib/neoscan/addresses/addresses.ex, apps/neoscan/test/addresses_test.exs, apps/neoscan_web/lib/neoscan_web/api.ex, apps/neoscan_web/lib/neoscan_web/templates/address/address.html.eex, apps/neoscan_web/lib/neoscan_web/templates/shared/transaction_panel_entries.html.eex, apps/neoscan_web/test/neoscan_web/controllers/api_controller_test.exs
=> Show nep5 symbol

apps/neoscan_web/lib/neoscan_web/resolvers/block.ex, apps/neoscan_web/lib/neoscan_web/schema/block_types.ex, apps/neoscan_web/test/neoscan_web/schema/query/block_test.exs
- Adding schema to query one block
- Improving the grapqhQL documentation
=> add schema for single block query

.gitignore, apps/neoscan_web/lib/neoscan_web/api.ex, apps/neoscan_web/test/neoscan_web/controllers/api_controller_test.exs
=> fix attributes

apps/neoscan/lib/neoscan/transactions/transactions.ex, apps/neoscan/test/transactions_test.exs, apps/neoscan_web/lib/neoscan_web/api.ex, apps/neoscan_web/lib/neoscan_web/resolvers/address.ex, apps/neoscan_web/lib/neoscan_web/resolvers/block.ex, apps/neoscan_web/lib/neoscan_web/schema.ex, apps/neoscan_web/lib/neoscan_web/schema/address_types.ex, apps/neoscan_web/test/neoscan_web/schema/query/address_test.exs, apps/neoscan_web/test/neoscan_web/schema/query/block_test.exs
=> add address graphql endpoint address

apps/neoscan_sync/lib/neoscan_sync/syncer.ex
=> Better logging

README.md, docker-compose-test-net.yml
This also adds some notes and tips.
=> Update readme et al to bring up testnet on source instead of docker

README.md, apps/neoscan_node/config/config.exs
Fixes some typos and...
Swaps:
"https://m1.neo.neonexchange.org",
"https://m2.neo.neonexchange.org",
"https://m3.neo.neonexchange.org",
"https://m4.neo.neonexchange.org",
"https://m5.neo.neonexchange.org"
for:
"https://m1.neo.nash.io",
"https://m2.neo.nash.io",
"https://m3.neo.nash.io",
"https://m4.neo.nash.io",
"https://m5.neo.nash.io"
=> Chore/Change Seed Nodes
